FROM openjdk:11
LABEL maintainer="Spring_jpa_resttemplate"
ADD target/BuiQuangHuuRestTemplate-0.0.1-SNAPSHOT.jar spring_data_jpa_callrestTemplate.jar
ENTRYPOINT ["java","-jar","spring_data_jpa_callrestTemplate.jar"]