version: "3.7"

services:
  buiquanghuu:
    build:
      context: ../BuiQuangHuu
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  buiquanghuuresttemplate:
    build:
      context: ../BuiQuangHuuRestTemplate
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - buiquanghuu

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: customerDB
      MYSQL_ROOT_PASSWORD: root

